### ISSUE TITLE
Parameters for shouldVisit()

### ISSUE THREAD

**Issue by ayseyo** [yasserg/crawler4j#229]
Hi, is there a way to pass parameters to shouldVisit() method? I want to be able to give "params1" or "params2" string dynamically to the method. I have searched for it and noticed that there is setCustomData() method on controller but I couldn't exactly understand how to do it.

@Override
    public boolean shouldVisit(Page referringPage, WebURL url) {
        return url.getURL().startsWith(params1") && url.getURL().contains("params2");
    }

**Comment by s17t** [comment]
Hi, 
 when you instance the WebController you can populate customData field:

```java
CrawlController crawler = new CrawlController()
...
crawler.setCustomData(myCustom);
```

And then in your `WebCrawler` extend you will able the retreive it, e.g. in `shouldVisit` method:

```java
public boolean shouldVisit(Page referringPage, WebURL url) {
...
myController.getCustomData();
...
}
```

However this way is quite dangerous because you will loose type safety. 

I recommend to use a factory to build your `CrawlController` injecting your custom (typed) data in the constructor and then to single instances of `WebCrawler` as showed in the README [here](https://github.com/yasserg/crawler4j#using-factory) (change `Map<String, String> metadata` with your custom typed data or repository).
