### ISSUE TITLE
Logging is tied to logback-classic

### ISSUE THREAD

**Issue by acarv** [yasserg/crawler4j#242]
Logging is tied to logback-classic it should only depend on slf4j-api in order to allow other implementations to be used.
For my project this is a show-stopper.

**Comment by Chaiavi** [comment]
If Crawler4J was only a library - I would agree.

But since it is a full program which can and should be run as a standalone
(after your own configurations) then it has to have some sort of simple
implementation.

Logback classic is very light and tightly integrated with slf4j.



But since it uses Maven, you can easily change the POM file and load any
other implementation while removing the current one.



Avi

**Comment by acarv** [comment]
I see your point. It makes sense.
I've managed to remove the dependency.
Thank you.
André
