### ISSUE TITLE
Is it possible to know pending URLs to crawl and estimated time left?

### ISSUE THREAD

**Issue by pw6591** [yasserg/crawler4j#255]

**Comment by Quix0r** [comment]
The short answer: **No**

The longer answer: To predict how much is left, you need to know how much are available in total which is only known (and that may vary later due to page changes) when you crawl them.

You _may_ only know how many of your starting URLs (aka seed URLs) are left to crawl because that list of total URLs is known. But then crawl4j must somehow track what seed URL is completed and what is pending (then you know how much of them are left) and I think that is not implemented.
