### ISSUE TITLE
Focused crawling using crawler4j

### ISSUE THREAD

**Issue by Karan-Daiict** [yasserg/crawler4j#277]
Can anyone suggest me, about how to go directly to certain depth instead of storing data of all pages. 
i.e. From A->B->C, if I have to go to C without storing data of A and B.
How can this be done using crawler4j.

Please assist....Thank you.

**Comment by Chaiavi** [comment]
Data/html is not stored only the links are stored.

That cannot be changed as these urls need to be stored in order to check
against them to see if they were already crawled.

That should not bother you though as they won't take much memory.

**Comment by Karan-Daiict** [comment]
Suppose A->B->C. Here B has multiple links and each link has multiple links in C.
Can I get all the links in C and B?

**Comment by Chaiavi** [comment]
In order to use crawler4j you implement WebCrawler
In it you should override the visit(Page page) method.

It defines the pages you want to parse and do something about.
In the Page class you will find a WebUrl member.
That class contains a member called depth

So use the depth member to discern if this is a url in a depth you want to parse, thus you can have an if statement which will enable parsing of the page only if the depth is 2 or 3 for example.

Hope this helps.

Avi.

**Comment by Karan-Daiict** [comment]
yes, working fine.
Thanks.
